Timeline Modal
dhmit/self-sustaining-cities pull request #9
Opened 2022-01-20 22:00 UTC by phuang00

This PR:

- creates the `DocumentModal` and children component to display an article of the timeline
- updates the project to use Bootstrap 5 and react-bootstrap 2.1.1 and updates previous navbar stylings
- creates a sample timeline page to show how `DocumentModal` is used (found at http://localhost:8000/timeline-test)

2022-01-21 16:16 UTC, anastasia requested changes
Hey, really great work. 
I only have one `to do` but it's a big one, and it is also my fault — for which I apologize. I will post this in the group channel also.
For this project, we have decided to move away from importing STYLES directly into our React components. The main reason behind that is that is it's really difficult to use in development — debugging styles and scoping become very complex when our app is compiled and we're looking at something that's called `zgnKfzkW1Yy6JWrJlX1mHA=="` instead of `class-1`. 
If you could please move to using regular old scss, that would be great! We can have all the document styles live in `/scss/document.scss` and have that stylesheet be imported in `scss/index.scss`. This does mean that the styles become available to the entire app, so we need to be careful with scoping the styles. 
Happy to pair on this, I know this is quite a big task. Let me know if you have any questions or if anything needs clarification.

2022-01-21 16:16 UTC, anastasia commented on frontend/components/DocumentModal.js
> +                    ? <div>Loading document...</div>
great use of the ternary operator!

2022-01-21 21:12 UTC, phuang00 commented
We've updated the styles for the timeline modal. They're all under `/scss/document.scss` now!

2022-01-23 02:30 UTC, anastasia commented
Great, thank you!

2022-01-23 02:31 UTC, merged